### PR TITLE
Feat data generator

### PR DESCRIPTION
**Pull request by ryanakiyama**

### CODE REVIEW

**Review by christine-w — COMMENTED** [review]
Overall comments:
- It looks like some of the features in this PR are not yet complete. As much as possible, merge working code for complete features. For example, console logging the generated data is appropriate for debugging during development but likely not the final functionality for the feature, and therefore, should not be merged into master.
- Schema.sql could have been its own PR since it is standalone and complete (i.e., a db script that can be used to create the tables and insert some seed data).

.eslintrc.js
 - Are you not getting an error without the comma on line 2?

database/index.js
- Please remove commented code that won't be used.
- insertListings does not do what I would have expected (i.e., insert records into a database table). Is this intentional? It looks incomplete.

package.json
- Are all these actually dependencies for the project? I am wondering because I am not seeing them used in the other files in this commit. Please remove packages that are not actually dependencies for the project.

schema.sql
- Inconsistent casing of keywords
- Is the choice to use CHAR instead of VARCHAR intentional?
- In the listings table, what would the value be in the not nullable column "rating" if rating_count = 0 (i.e., the listing did not have ratings yet)?
- I believe the team had agreed on ratings being a score out of 100 (seeing 4.5 in your test data)

data-generator.js
- Suggest adding 'entire home' to the list of roomTypes
- Noticed that the roomType is 'shared' in this list but 'shared room' in the test data inserts in schema.sql. Let's converge as a team on which one to use.
- If houseAmenities will not vary by listing, it would be better code organization to declare and define that with the other const variables. Note that this should also be a const as well since it never gets reassigned. (linter didn't complain?)
- For the definition of listingName, please consider using ES6 template literals.
- For the generation of nightly prices, consider functions to generate the random date and price. (DRY)

server/index.js
- Please remove commented out code that won't be used.
- Confusing that a get route handler uses an insertion db method (as suggested by the name "insertListings").
- Also confusing that a /reservations route is providing/inserting listing data
- What is happening to the generated listings data? It doesn't appear to be sent back in the response. Based on what is in database/index.js, it also is not getting inserted into the database. Possibly incomplete?

**Review by christine-w — CHANGES_REQUESTED** [review]
I would suggest merging schema.sql and data generator independently after cleaning up the items in the review comments (left earlier in the thread).

database/index.js and server/index.js should be completed before merging.

**Review by christine-w — APPROVED** [review]

**Review by christine-w — COMMENTED** [review]
server/data-generator.js now only generates a single nightly price for each listing, which I assume is not desirable. The change made wasn't quite what I was suggesting. Let's chat if you want to be able to generate more nightly prices for each listing.

**Comment by ryanakiyama** [comment]
@christine-w please take a look at the changes made, here are the main points

- Added room types and changed around variable declarations/syntax, example data generation is not in the production stage and was just created a random data generator at the mvp level, will keep on iterating on the variety of random data being generated

- Updated the schema.sql and pushed it to my earlier pull request

- Removed incomplete database helper functions

**Pull request merged**
